### ISSUE TITLE
destination node error

### ISSUE THREAD

**Issue by prasad145** [K-G-PRAJWAL/ReactJS-Projects#8]
if i set random destination node , can't able to see the visualization!!!

**Comment by K-G-PRAJWAL** [comment]
Please mention which project you are referring to.

**Comment by prasad145** [comment]
Ohh sorry!, in Path finding Visualization.

**Comment by K-G-PRAJWAL** [comment]
The path-finding-visualizer project currently doesn't have the functionality to set a destination node by the user because it's predefined. But it may be a feature to work on in the future.

**Comment by prasad145** [comment]
Okay, Thanks for responding!!
