### ISSUE TITLE
Improving on the README for the project Breaking Bad.

### ISSUE THREAD

**Issue by saurabhyadav-gith** [K-G-PRAJWAL/ReactJS-Projects#9]
Hey, I find this project really good but the README can be improved to provide a better insight of the project. There are certain things that can be improved. Like:
- [x] Adding tags for technologies used.
- [x] Putting certain tags to help beginners fork and clone the project.

**Comment by K-G-PRAJWAL** [comment]
Your README update for Breaking Bad project has been merged.
